### ISSUE TITLE
Display admin notice if Simple Page Ordering plugin is not installed/activated

### ISSUE THREAD

**Issue by AaronHolbrook** [10up/curator#11]
Would be helpful to remind users to install Simple Page Ordering plugin, as Curator is much more usable with it.

**Comment by ayebare** [comment]
Since The Ordering plugin is not explicitly required. I believe this notice should give the user an option not to show it. i.e a ( Don't show this again link ) within the notice.

**Comment by AaronHolbrook** [comment]
@ayebare true; also would be nice to be able to simply prevent message from showing via a filter (i.e. you know for sure you don't want it in your project)
