### ISSUE TITLE
PHP Notices when not using Pinner or Featurer 

### ISSUE THREAD

**Issue by jamesmehorter** [10up/curator#20]
Fresh install, added two post types w/ cur_set_post_types, did not enable pinning or featuring.

![screen shot 2015-04-10 at 9 50 39 am](https://cloud.githubusercontent.com/assets/491189/7089127/7d887c00-df67-11e4-8169-85b7225c1995.jpg)

Notice:  Trying to get property of non-object in /srv/www/guns/htdocs/wp-content/plugins/curator-master/includes/class-cpt-curator.php on line 469

Notice:  Trying to get property of non-object in /srv/www/guns/htdocs/wp-content/plugins/curator-master/includes/class-cpt-curator.php on line 485

**Comment by AaronHolbrook** [comment]
Thanks @jamesmehorter
