### ISSUE TITLE
i18n functions use 'fpb' domain

### ISSUE THREAD

**Issue by jamesmehorter** [10up/curator#22]
It appears all translation strings use the 'fpb' domain. e.g. `__( 'Pinned', 'fpb' );`

Ideally one could set the domain via a filter.

**Comment by AaronHolbrook** [comment]
Ha, that's an accidental carry over from flipboard

**Comment by AaronHolbrook** [comment]
I don't think a filter for this would be appropriate. I think a simple `cur` or `curator` would be more appropriate as the text-domain is enclosed in just this plugin

**Comment by AaronHolbrook** [comment]
Fixed by https://github.com/10up/curator/commit/5548b8862cfa596e0952876ce3dadd022f5dcf53

Thanks @jamesmehorter for the report
