### ISSUE TITLE
Any Guide / Tutorial for Curator?

### ISSUE THREAD

**Issue by vilav** [10up/curator#26]
Hi there,

I'm new to creating with wordpress but Curator seems like a great solution for what I'm trying to achieve. Any guide / video on how to use Curator? I'm using the 2016 Wordpress theme and I'm not where to start as I only see a blank window:

<img width="1261" alt="screenshot 2015-12-16 00 17 08" src="https://cloud.githubusercontent.com/assets/849098/11816194/5cb5a7c2-a38a-11e5-9c0e-688004983d2f.png">

**Comment by AaronHolbrook** [comment]
Hi @vilav,
Have you read through the readme? It's chock full of good information on how to use/implement this plugin.

**Comment by vilav** [comment]
Hi @AaronHolbrook! Thanks for responding. I think I'm missing the code snippet injection.
Do I add the 2 code snippets (for cur_set_post_types & cur_modules) to header.php?

**Comment by vilav** [comment]
Just adding 1 more question to the lot:

Is this a valid use case for Curator - Example site:http://beta.oreilly.com/
(Different posts are grouped under a section and several such sections are shown on the same page.)

**Comment by AaronHolbrook** [comment]
@vilav typically you'd add those to your functions.php file in your theme. 

header.php is a template file, that although typically gets included in every page load (when you call get_header() ), it's still not a great idea to put functional logic in template files.

> Is this a valid use case for Curator - Example site:http://beta.oreilly.com/
(Different posts are grouped under a section and several such sections are shown on the same page.)

Hmm, I suppose. The main purpose of Curator was to provide a way to manually order a selection of posts that exist in different post types. I.e., being able to feature a selection of posts that differ so much they are different post types, not just different taxonomies (taxonomies being the way that you categorize things).

Hope that helps, good luck @vilav !

**Comment by vilav** [comment]
@AaronHolbrook thank you so much for the instructions. I'm able to curate the posts in the admin interface. I'm now to get the curated items to output to a page. Is there a short code that i can use to pull  the curator instance by name?

Or do I post the following code snippet into an index.php. Sorry about the noob questions.

		<?php $args = array(
		    'post_type' => 'cur-curator',
		);
		
		$curated_posts = new WP_Query( $args );
		
		if ( $curated_posts->have_posts() ) : while ( $curated_posts->have_posts() ) : $curated_posts->the_post();
		
		    // Set our default to not be featured
		    $featured = false;
		
		    // Ensure this function exists, if you don't wrap the function call and then deactivate the plugin you will cause a fatal error in your installation
		    if ( function_exists( `cur_is_featured` ) ) {
		        $featured = cur_is_featured();
		    }
		
		endwhile; endif; ?>

**Comment by AaronHolbrook** [comment]
Hi @vilav, no problem!

You can query for curated posts simply by building a typical WP_Query, but using the cur-curator post type: https://github.com/10up/curator#querying
